# strongSwan classic ipsec.conf - Deprecated & Insecure (3DES / HMAC-MD5 / MODP-1024) (initiator)
config setup
    charondebug="ike 2, knl 2, cfg 2, esp 2"

conn %default
    keyexchange=ikev2
    authby=secret
    dpdaction=restart
    dpddelay=30s

conn insecure_deprecated_3des_md5
    left=10.10.0.2
    leftid=@initiator.lab.local
    leftsubnet=192.168.10.0/24
    right=10.10.0.3
    rightid=@responder.lab.local
    rightsubnet=192.168.20.0/24
    ike=3des-md5-modp1024!
    esp=3des-md5!
    type=tunnel
    auto=start
