"""
Testbed Configuration Matrix Generator for IPsec VPN Lab.
Generates strongSwan (>=6.0) configuration pairs (initiator & responder)
spanning Mode x Cipher x DH-Group (incl. PQC ML-KEM-768) x PFS x IP version.
"""

import json
import os
from typing import Dict, List, Any


class IPsecMatrixGenerator:
    """
    Generates strongSwan configuration files and Docker Compose environments
    for empirical IPsec protocol testing and dataset creation.
    """

    CIPHER_SUITES = [
        {
            "id": "pqc_hybrid_quantum_safe",
            "name": "PQC Hybrid ML-KEM-768 (Quantum Resilient)",
            "ike_proposal": "aes256-sha384-ecp384-ke1_mlkem768!",
            "esp_proposal": "aes256gcm128-sha384-ecp384!",
            "mode": "tunnel",
            "pfs": True,
            "dh_group": "ML-KEM-768 + ECP-384 (Hybrid RFC 9370)",
            "security_tier": "PQC_COMPLIANT",
            "nist_status": "FIPS 203 / RFC 9370 (Quantum-Safe Transition)",
        },
        {
            "id": "nist_approved_aes_gcm_256",
            "name": "NIST High-Assurance (AES-256-GCM / ECP-384)",
            "ike_proposal": "aes256gcm16-prfsha384-ecp384!",
            "esp_proposal": "aes256gcm16-ecp384!",
            "mode": "tunnel",
            "pfs": True,
            "dh_group": "ECP-384 (Group 20)",
            "security_tier": "NIST_APPROVED",
            "nist_status": "NIST SP 800-77 Rev. 1 Approved",
        },
        {
            "id": "nist_standard_aes_cbc_256",
            "name": "NIST Standard (AES-256-CBC / HMAC-SHA256 / MODP-2048)",
            "ike_proposal": "aes256-sha256-modp2048!",
            "esp_proposal": "aes256-sha256-modp2048!",
            "mode": "tunnel",
            "pfs": True,
            "dh_group": "MODP-2048 (Group 14)",
            "security_tier": "NIST_APPROVED",
            "nist_status": "NIST SP 800-77 Rev. 1 Approved",
        },
        {
            "id": "legacy_acceptable_aes_128",
            "name": "Acceptable Legacy (AES-128-CBC / No PFS)",
            "ike_proposal": "aes128-sha256-modp2048!",
            "esp_proposal": "aes128-sha256!",
            "mode": "tunnel",
            "pfs": False,
            "dh_group": "MODP-2048 (Group 14, IKE only)",
            "security_tier": "ACCEPTABLE_LEGACY",
            "nist_status": "NIST SP 800-77 Rev. 1 Acceptable / Missing PFS",
        },
        {
            "id": "insecure_deprecated_3des_md5",
            "name": "Deprecated & Insecure (3DES / HMAC-MD5 / MODP-1024)",
            "ike_proposal": "3des-md5-modp1024!",
            "esp_proposal": "3des-md5!",
            "mode": "tunnel",
            "pfs": False,
            "dh_group": "MODP-1024 (Group 2, Deprecated)",
            "security_tier": "INSECURE_DEPRECATED",
            "nist_status": "NIST SP 800-77 Rev. 1 & RFC 8247 Disallowed",
        },
        {
            "id": "transport_mode_aes_gcm",
            "name": "Transport Mode Host-to-Host (AES-128-GCM / ECP-256)",
            "ike_proposal": "aes128gcm16-prfsha256-ecp256!",
            "esp_proposal": "aes128gcm16-ecp256!",
            "mode": "transport",
            "pfs": True,
            "dh_group": "ECP-256 (Group 19)",
            "security_tier": "NIST_APPROVED",
            "nist_status": "NIST SP 800-77 Rev. 1 Approved (Host Security)",
        },
    ]

    def __init__(self, output_dir: str = "testbed/generated_configs"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_swanctl_conf(self, suite: Dict[str, Any], is_initiator: bool = True) -> str:
        role = "initiator" if is_initiator else "responder"
        local_ip = "10.10.0.2" if is_initiator else "10.10.0.3"
        remote_ip = "10.10.0.3" if is_initiator else "10.10.0.2"
        local_ts = "192.168.10.0/24" if is_initiator else "192.168.20.0/24"
        remote_ts = "192.168.20.0/24" if is_initiator else "192.168.10.0/24"

        mode_str = "tunnel" if suite["mode"] == "tunnel" else "transport"
        start_action = "start" if is_initiator else "none"

        conf = f"""# strongSwan 6.0+ swanctl configuration - {suite['name']} ({role})
# Generated by IPsec Matrix Generator

connections {{
    vpn-{suite['id']} {{
        version = 2
        local_addrs = {local_ip}
        remote_addrs = {remote_ip}
        proposals = {suite['ike_proposal']}
        rekey_time = 3600s
        dpd_delay = 30s
        
        local {{
            auth = psk
            id = vpn-{role}@lab.local
        }}
        
        remote {{
            auth = psk
            id = vpn-{'responder' if is_initiator else 'initiator'}@lab.local
        }}
        
        children {{
            net-tunnel {{
                mode = {mode_str}
                esp_proposals = {suite['esp_proposal']}
                local_ts = {local_ts}
                remote_ts = {remote_ts}
                rekey_time = 1800s
                start_action = {start_action}
                dpd_action = restart
                close_action = restart
            }}
        }}
    }}
}}

secrets {{
    ike-vpn-{suite['id']} {{
        id-1 = vpn-initiator@lab.local
        id-2 = vpn-responder@lab.local
        secret = "IPsecSecurityAuditMatrixLabKey2026!Offline"
    }}
}}
"""
        return conf

    def generate_ipsec_conf(self, suite: Dict[str, Any], is_initiator: bool = True) -> str:
        """Classic ipsec.conf syntax for legacy compatibility."""
        role = "initiator" if is_initiator else "responder"
        left = "10.10.0.2" if is_initiator else "10.10.0.3"
        right = "10.10.0.3" if is_initiator else "10.10.0.2"
        leftsubnet = "192.168.10.0/24" if is_initiator else "192.168.20.0/24"
        rightsubnet = "192.168.20.0/24" if is_initiator else "192.168.10.0/24"
        auto = "start" if is_initiator else "add"

        conf = f"""# strongSwan classic ipsec.conf - {suite['name']} ({role})
config setup
    charondebug="ike 2, knl 2, cfg 2, esp 2"

conn %default
    keyexchange=ikev2
    authby=secret
    dpdaction=restart
    dpddelay=30s

conn {suite['id']}
    left={left}
    leftid=@{role}.lab.local
    leftsubnet={leftsubnet}
    right={right}
    rightid=@{'responder' if is_initiator else 'initiator'}.lab.local
    rightsubnet={rightsubnet}
    ike={suite['ike_proposal']}
    esp={suite['esp_proposal']}
    type={suite['mode']}
    auto={auto}
"""
        return conf

    def generate_docker_compose(self) -> str:
        """Emits complete reproducible multi-node Docker Compose specification."""
        compose = """version: '3.8'

services:
  initiator:
    image: strongswan/strongswan:6.0.7
    container_name: ipsec_initiator
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./generated_configs/initiator:/etc/swanctl/conf.d
    networks:
      vpn_net:
        ipv4_address: 10.10.0.2
    command: ["charon-systemd"]

  responder:
    image: strongswan/strongswan:6.0.7
    container_name: ipsec_responder
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./generated_configs/responder:/etc/swanctl/conf.d
    networks:
      vpn_net:
        ipv4_address: 10.10.0.3
    command: ["charon-systemd"]

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
"""
        return compose

    def generate_all(self) -> Dict[str, Any]:
        """Generates all config pairs and writes to disk."""
        init_dir = os.path.join(self.output_dir, "initiator")
        resp_dir = os.path.join(self.output_dir, "responder")
        os.makedirs(init_dir, exist_ok=True)
        os.makedirs(resp_dir, exist_ok=True)

        manifest = []
        for suite in self.CIPHER_SUITES:
            # swanctl.conf
            init_conf = self.generate_swanctl_conf(suite, is_initiator=True)
            resp_conf = self.generate_swanctl_conf(suite, is_initiator=False)
            
            init_path = os.path.join(init_dir, f"{suite['id']}.conf")
            resp_path = os.path.join(resp_dir, f"{suite['id']}.conf")
            
            with open(init_path, "w", encoding="utf-8") as f:
                f.write(init_conf)
            with open(resp_path, "w", encoding="utf-8") as f:
                f.write(resp_conf)

            # Classic ipsec.conf
            init_ipsec_path = os.path.join(init_dir, f"ipsec_{suite['id']}.conf")
            resp_ipsec_path = os.path.join(resp_dir, f"ipsec_{suite['id']}.conf")
            with open(init_ipsec_path, "w", encoding="utf-8") as f:
                f.write(self.generate_ipsec_conf(suite, is_initiator=True))
            with open(resp_ipsec_path, "w", encoding="utf-8") as f:
                f.write(self.generate_ipsec_conf(suite, is_initiator=False))

            manifest.append({
                "suite_id": suite["id"],
                "name": suite["name"],
                "security_tier": suite["security_tier"],
                "ike_proposal": suite["ike_proposal"],
                "esp_proposal": suite["esp_proposal"],
                "dh_group": suite["dh_group"],
                "pfs": suite["pfs"],
                "mode": suite["mode"],
                "initiator_conf": init_path,
                "responder_conf": resp_path,
            })

        compose_path = os.path.join(self.output_dir, "docker-compose.yml")
        with open(compose_path, "w", encoding="utf-8") as f:
            f.write(self.generate_docker_compose())

        manifest_path = os.path.join(self.output_dir, "matrix_manifest.json")
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)

        return {"status": "success", "suites_generated": len(manifest), "manifest_path": manifest_path}


if __name__ == "__main__":
    gen = IPsecMatrixGenerator()
    res = gen.generate_all()
    print(f"Generated {res['suites_generated']} IPsec matrix testbed configurations.")
